services:
  frontend:
    platform: linux/amd64
    build:
      context: ./frontend/shuppi-ui
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./frontend/shuppi-ui:/app
      - /app/node_modules
    working_dir: /app
    # command: npm run dev
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/ShuppiApi
      dockerfile: Dockerfile
    ports:
      - "5075:5075"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
    volumes:
      - ./backend/ShuppiApi:/app
    working_dir: /app
    command: dotnet run --urls http://0.0.0.0:5075
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
